[package]
name = "yuv-sys"
version = "0.1.0"
authors = ["mhornick <mhornick@redhat.com>"]
edition = "2018"
build = "build.rs"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
